repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - ro-crate-metadata.json
  rocrate_metadata_validation: False
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - nextflow_schema.json
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: autopolish
  description: Automated end-to-end assembly of bacterial genomes from Oxford Nanopore
    Technology (ONT) long-read sequencing data.
  author: Julissa Zelaya
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - nf_schema
    - gpu
  is_nfcore: true
