# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "polypolish_filter"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "polypolish":
      description: "Polishing genome assemblies with short reads."
      homepage: "https://github.com/rrwick/Polypolish/wiki"
      documentation: "https://github.com/rrwick/Polypolish/wiki"
      tool_dev_url: "https://github.com/rrwick/Polypolish"
      doi: ""
      licence: ["GPL v3-or-later"]
      identifier: biotools:polypolish

input:
  # TODO nf-core: Update the information obtained from bio.tools and make sure that it is correct
  - - meta:
        type: map
        description: Groovy Map containing sample information. e.g. `[
          id:'sample1' ]`
    - sequence:
        type: file
        description: sequence file
        pattern: "*.{fasta}"
        ontologies:
          - edam: http://edamontology.org/data_2044 # Sequence
          - edam: http://edamontology.org/format_1929 # FASTA
output:
  ### TODO nf-core: Add a description of all of the variables used as output
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{bam,cram,sam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
            - edam: "http://edamontology.org/format_2573" # CRAM
            - edam: "http://edamontology.org/format_3462" # SAM
  versions_polypolish:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "polypolish":
          type: string
          description: The name of the tool
      - "polypolish --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - polypolish:
          type: string
          description: The name of the tool
      - polypolish --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@julissazelaya"
maintainers:
  - "@julissazelaya"
